/**
 * Small global calibration surface for racecraft behavior.
 *
 * These are policy/controller quantities shared by every track. Geometry,
 * vehicle dimensions, rule clearances, and state-machine release thresholds
 * are deliberately not calibration dimensions.
 */
export interface RacecraftCalibration {
  predictionHorizonSeconds: number;
  blueFlagTimeToCatchSeconds: number;
  qualifyingTimeToCatchSeconds: number;
  brakingPrudence: number;
  towRangeM: number;
  wakeSpreadRate: number;
  towDragReduction: number;
  dirtyAirMarginPenalty: number;
  mistakeUtilizationRate: number;
  nearRubClearanceMetres: number;
  defensiveBlockNoticeSeconds: number;
}

export interface RacecraftCalibrationDefinition {
  key: keyof RacecraftCalibration;
  unit: 'm/s' | 'm' | 's' | 'm/s^2' | 'fraction' | '1/s';
  minimum: number;
  maximum: number;
  rationale: string;
  owner: string;
}

/** Numerical resolution only; changing this must not author behavior. */
export interface RacecraftResolution {
  stationSamples: number;
}

/** Hard nearby-pair work bound from the 30 Hz traffic runtime contract. */
export const TRAFFIC_NEIGHBOR_SCAN_METRES = 60;
/** Wider bounded scan reserved for stopped or source-revoked occupancy. */
export const OBSTACLE_NEIGHBOR_SCAN_METRES = 160;

export const RACECRAFT_CALIBRATION_DEFAULTS: Readonly<RacecraftCalibration> = Object.freeze({
  predictionHorizonSeconds: 2.4,
  blueFlagTimeToCatchSeconds: 4,
  qualifyingTimeToCatchSeconds: 5,
  brakingPrudence: 0.7,
  // Covers roughly one second at the start of a long-straight run; strength
  // still grows continuously as the physical gap closes.
  towRangeM: 32,
  wakeSpreadRate: 0.04,
  towDragReduction: 0.18,
  dirtyAirMarginPenalty: 0.001,
  mistakeUtilizationRate: 0.01,
  nearRubClearanceMetres: 0.15,
  defensiveBlockNoticeSeconds: 1
});

export const RACECRAFT_RESOLUTION_DEFAULTS:
Readonly<RacecraftResolution> = Object.freeze({
  stationSamples: 12
});

export const RACECRAFT_CALIBRATION_DEFINITIONS:
readonly RacecraftCalibrationDefinition[] = Object.freeze([
  {
    key: 'predictionHorizonSeconds', unit: 's', minimum: 1.5, maximum: 3.5,
    rationale: 'Fixed time horizon for conservative maneuver feasibility sampling.',
    owner: 'maneuver feasibility'
  },
  {
    key: 'blueFlagTimeToCatchSeconds', unit: 's', minimum: 3, maximum: 7,
    rationale: 'Blue-flag acquisition horizon for an eligible one-lap-ahead catch.',
    owner: 'priority state'
  },
  {
    key: 'qualifyingTimeToCatchSeconds', unit: 's', minimum: 3.5, maximum: 8,
    rationale: 'Qualifying-priority acquisition horizon for a flying-lap catch.',
    owner: 'priority state'
  },
  {
    key: 'brakingPrudence', unit: 'fraction', minimum: 0.55, maximum: 0.85,
    rationale: 'Bounded share of available braking used when predicting traffic and queue stops.',
    owner: 'brake reachability'
  },
  {
    key: 'towRangeM', unit: 'm', minimum: 16, maximum: 32,
    rationale: 'Minimum half-strength scale of the smooth wake; high-speed range grows with speed.',
    owner: 'aerodynamic traffic coupling'
  },
  {
    key: 'wakeSpreadRate', unit: 'fraction', minimum: 0.01, maximum: 0.12,
    rationale: 'Wake-plume half-width growth per downstream metre; body overlap converts it to drag and grip effects.',
    owner: 'aerodynamic traffic coupling'
  },
  {
    key: 'towDragReduction', unit: 'fraction', minimum: 0.1, maximum: 0.25,
    rationale: 'Maximum drag-coefficient reduction generated by a fully aligned slipstream.',
    owner: 'aerodynamic traffic coupling'
  },
  {
    key: 'dirtyAirMarginPenalty', unit: 'fraction', minimum: 0, maximum: 0.006,
    rationale: 'Small grip loss gated by actual lateral load while following in another car\'s wake.',
    owner: 'aerodynamic traffic coupling'
  },
  {
    key: 'mistakeUtilizationRate', unit: '1/s', minimum: 0.0025, maximum: 0.04,
    rationale: 'Per-second mistake hazard at full grip utilization, minimum focus, and dry conditions.',
    owner: 'driver utilization clock'
  },
  {
    key: 'nearRubClearanceMetres', unit: 'm', minimum: 0.05, maximum: 0.3,
    rationale: 'Soft body-edge daylight band for planned alongside exposure; hard legality remains exact physical width.',
    owner: 'sporting near-rub preference'
  },
  {
    key: 'defensiveBlockNoticeSeconds', unit: 's', minimum: 0.5, maximum: 2,
    rationale: 'Minimum physically observable notice before a defender may close an optional approach side.',
    owner: 'sporting defensive-block safety'
  },
]);

let active: Readonly<RacecraftCalibration> = RACECRAFT_CALIBRATION_DEFAULTS;
let activeResolution: Readonly<RacecraftResolution> =
  RACECRAFT_RESOLUTION_DEFAULTS;

export function racecraftCalibration(): Readonly<RacecraftCalibration> {
  return active;
}

export function racecraftResolution(): Readonly<RacecraftResolution> {
  return activeResolution;
}

function validateCalibration(calibration: Readonly<RacecraftCalibration>): void {
  for (const definition of RACECRAFT_CALIBRATION_DEFINITIONS) {
    const value = calibration[definition.key];
    if (!Number.isFinite(value) || value < definition.minimum || value > definition.maximum)
      throw new Error(
        `${definition.key} must be finite and within ` +
        `[${definition.minimum}, ${definition.maximum}] ${definition.unit}`
      );
  }
}

function validateResolution(resolution: Readonly<RacecraftResolution>): void {
  if (!Number.isInteger(resolution.stationSamples) ||
      resolution.stationSamples <= 0)
    throw new Error('stationSamples must be a positive integer');
}

/** Run one synchronous headless experiment with a bounded global override. */
export function withRacecraftCalibration<T>(
  overrides: Partial<RacecraftCalibration>,
  run: () => T
): T {
  const previous = active;
  const candidate = Object.freeze({ ...previous, ...overrides });
  validateCalibration(candidate);
  active = candidate;
  try {
    return run();
  } finally {
    active = previous;
  }
}

/** Run one synchronous convergence experiment at an alternate resolution. */
export function withRacecraftResolution<T>(
  overrides: Partial<RacecraftResolution>,
  run: () => T
): T {
  const previous = activeResolution;
  const candidate = Object.freeze({ ...previous, ...overrides });
  validateResolution(candidate);
  activeResolution = candidate;
  try {
    return run();
  } finally {
    activeResolution = previous;
  }
}
